---
booktitle: Proceedings of the 1st International Workshop on Medication and Adverse
  Drug Event Detection
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
shortname: MADE1.0
volume: 90
year: '2018'
start: 2018-05-04
end: 2018-05-04
published: 2018-05-16
url: http://proceedings.mlr.press
author:
  name: PMLR
location: Worcester, USA
layout: proceedings
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 2640-3498
id: MADE-2018
month: 0
cycles: false
editor:
- given: Feifan
  family: Liu
- given: Abhyuday
  family: Jagannatha
- given: Hong
  family: Yu
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 1st International Workshop on Medication and Adverse Drug Event Detection on 04 May 2018

  Published as Volume 90 by the Proceedings of Machine Learning Research on 16 May 2018.

  Volume Edited by:
    Feifan Liu
    Abhyuday Jagannatha
    Hong Yu

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 04 May
baseurl: "/v90"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v90
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: International Workshop on Medication and Adverse Drug Event Detection
  url: 
  location: 
  dates:
  - 2018-05-04
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
